[package]
name = "variables"
version = "0.1.0"
authors = ["ashok <ashok.kumar@dbaux.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-odd = "1.0.0"